/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as test from "./test";
export type { test };
export type { Campaign } from "./Campaign";
export type { CampaignFactory } from "./CampaignFactory";
export type { XoloRocket } from "./XoloRocket";
