/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockBep20Sol from "./MockBEP20.sol";
export type { mockBep20Sol };
export type { MockUniRouter } from "./MockUniRouter";
