/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ICampaign,
  ICampaignInterface,
} from "../../../contracts/interfaces/ICampaign";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_owner",
        type: "address",
      },
      {
        internalType: "uint16",
        name: "_fee",
        type: "uint16",
      },
      {
        internalType: "address",
        name: "_router",
        type: "address",
      },
      {
        components: [
          {
            internalType: "contract IERC20",
            name: "token",
            type: "address",
          },
          {
            internalType: "uint32",
            name: "start",
            type: "uint32",
          },
          {
            internalType: "uint32",
            name: "end",
            type: "uint32",
          },
          {
            internalType: "uint256",
            name: "presaleTokens",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "liquidityTokens",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "minPurchaseBnb",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "maxPurchaseBnb",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "softCap",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "tokensPerBnb",
            type: "uint256",
          },
          {
            internalType: "enum ICampaign.Dex",
            name: "dex",
            type: "uint8",
          },
          {
            internalType: "enum ICampaign.UnsoldTokensAction",
            name: "action",
            type: "uint8",
          },
          {
            internalType: "uint16",
            name: "liquidityPercent",
            type: "uint16",
          },
          {
            internalType: "uint32",
            name: "liquidityLockupPeriod",
            type: "uint32",
          },
        ],
        internalType: "struct ICampaign.Config",
        name: "_config",
        type: "tuple",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "raised",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ICampaign__factory {
  static readonly abi = _abi;
  static createInterface(): ICampaignInterface {
    return new utils.Interface(_abi) as ICampaignInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICampaign {
    return new Contract(address, _abi, signerOrProvider) as ICampaign;
  }
}
