/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ICampaign__factory } from "./ICampaign__factory";
export { ICampaignFactory__factory } from "./ICampaignFactory__factory";
