/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as mockBep20Sol from "./MockBEP20.sol";
export { MockUniRouter__factory } from "./MockUniRouter__factory";
